title:  Reviews of Ilya Sutskever's recommended reading list
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
kramdown:
  math_engine: mathjax
show_downloads: false